format_version: 10                # pipeline version from gocd, based on this options would vary 
pipelines: 
  backend:                                             # name of the pipeline job that will be showing on UI
    group: App-Deployments
    label_template: "${COUNT}"
    materials:
      mysql-code:
        git: https://github.com/B58-CloudDevOps/ansible.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    secure_variables:
        SSH_PSW: AES:vzIbSB15sUfo2tgn5LdCrg==:iskfYF7AUUosX4RYCWI2cw=
        VAULT_TOKEN: AES:VEFfZiO1g2xSNqTvxRI7DQ==:CLpdOAgnrAGOQiKgdRwLgvqkkRw9qLI2O9L5+vFoMyY=   
    environment_variables:
        COMPONENT: backend
    template: App-Deployment-Template