format_version: 10                # pipeline version from gocd, based on this options would vary 
pipelines: 
  expenses-create:                                            
    group: Terraform
    label_template: "${COUNT}"
    materials:
      mysql-code:
        git: https://github.com/CodingManoj/expense-terraform.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    secure_variables:
        SSH_PASSWORD: AES:vzIbSB15sUfo2tgn5LdCrg==:iskfYF7AUUosX4RYCWI2cw=
        VAULT_TOKEN: AES:VEFfZiO1g2xSNqTvxRI7DQ==:CLpdOAgnrAGOQiKgdRwLgvqkkRw9qLI2O9L5+vFoMyY=   
    environment_variables:
        ACTION: apply
    stages:                                       
      - dev:                                       
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          environment_variables: { env: dev }
          approval: { type: manual }
          jobs:
            terraform:
              tasks:
                - exec: { command: bash, arguments: ["run.sh"] }
      - prod:                                       
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          environment_variables: { env: prod }
          approval: { type: manual }
          jobs:
            terraform:
              tasks:
                - exec: { command: bash, arguments: ["run.sh"] }
