format_version: 10                
pipelines: 
  destroy:                                            
    group: Terraform
    label_template: "${COUNT}"
    materials:
      mysql-code:
        git: https://github.com/CodingManoj/expense-terraform.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    secure_variables:
        SSH_PASSWORD: AES:DzcBYlrtereGTKsbbbm/rw==:yn30rX0v4RIF34QJVliZRQ==
        VAULT_TOKEN: AES:VEFfZiO1g2xSNqTvxRI7DQ==:CLpdOAgnrAGOQiKgdRwLgvqkkRw9qLI2O9L5+vFoMyY=   
    environment_variables:
        ACTION: destroy
    stages:                                       
      - dev:                                       
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          environment_variables: { ENV: dev }
          approval: { type: manual }
          jobs:
            terraform:
              tasks:
                  - exec: { command: bash, arguments: ["init.sh"] }

      - prod:                                       
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          environment_variables: { ENV: prod }
          approval: { type: manual }
          jobs:
            terraform:
              tasks:
                  - exec: { command: bash, arguments: ["init.sh"] }

