format_version: 10                # pipeline version from gocd, based on this options would vary 
pipelines: 
  tools-create:                                            
    group: Terraform
    label_template: "${COUNT}"
    materials:
      mysql-code:
        git: https://github.com/CodingManoj/tools-automation.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    # secure_variables:
    #     SSH_PSW: DevOps321
    environment_variables:
        SSH_PSW: DevOps321
    stages:                                       
      - dev:                                       
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          jobs:
            creating-tools-infra:
              tasks:
                - exec: { command: terraform, arguments: ["init"] }
                - exec: { command: terraform, arguments: ["apply" , "-auto-approve"] }

