format_version: 10                # pipeline version from gocd, based on this options would vary 
pipelines: 
  tools-create:                                            
    group: Terraform
    label_template: "${COUNT}"
    materials:
      mysql-code:
        git: https://github.com/CodingManoj/tools-automation.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    secure_variables:
        SSH_PASSWORD: AES:DzcBYlrtereGTKsbbbm/rw==:yn30rX0v4RIF34QJVliZRQ==
        VAULT_TOKEN: AES:VEFfZiO1g2xSNqTvxRI7DQ==:CLpdOAgnrAGOQiKgdRwLgvqkkRw9qLI2O9L5+vFoMyY=   
    environment_variables:
        ACTION: apply
    stages:                                       
      - dev:                                       
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          jobs:
            creating-tools-infra:
              tasks:
                  - exec: { command: bash, arguments: ["run.sh"] }
