format_version: 10                # pipeline version from gocd, based on this options would vary 
pipelines: 
  vault-cm:                                            
    group: Tools-CM
    label_template: "${COUNT}"
    materials:
      vault:
        git: https://github.com/CodingManoj/tools-automation.git
        branch: main
        auto_update: true 
        shallow_clone: true
        display_order: -1
        lock_behavior: none
    # secure_variables:
    #     SSH_PSW: DevOps321
    environment_variables:
        tool_name: vault
        SSH_PASSWORD: DevOps321
    stages:                                       
      - dev:                                       
          fetch_materials: true 
          keep_artifacts: false
          clean_workspace: false
          approval: { type: manual }
          jobs:
            terraform:
              tasks:
                - exec: 
                    command: bash 
                    arguments:
                      - setup-tools-service.sh

